### ISSUE TITLE
Black Screen Issue

### ISSUE THREAD

**Issue by Bedict31** [Vincent4440/ASUS-TUF-F15-OPENCORE#4]
Everytime i'm booting into hackintosh, after apple logo the screen just go went black and i haveto wait for like 2-3mins before the screen go on.

**Comment by Vincent4440** [comment]
Try disabling verbose debugging, i had to increase the boot time to fix screen flicker issues but it takes about 1min for me to boot, you're using fx506lh right?

**Comment by Vincent4440** [comment]
Which macos version are you using?

**Comment by Bedict31** [comment]
Hi, i am using

**Comment by Bedict31** [comment]
Hi, i am using macOS 13 Ventura. Ill try and see if it'll fix it.

**Comment by Bedict31** [comment]
I am using fx506lh, i5-10300h gtx 1650 uhd 630. The trackpad buttons don't work but i don't see any problem there since i use external mouse. F1-f12 buttons won't work or can't be used to change volume and brightness. In macOS Ventura, you can't also change brightness.

**Comment by Bedict31** [comment]
i tried to disable verbose debugging, it still didn't fixed it.

**Comment by Vincent4440** [comment]
so i would recommend you to use monterey, catalina cause these are the only versions i have tested and i wasnt facing any boot problem like this and i also wasnt facing any issues related to trackpad

**Comment by Bedict31** [comment]
Alright, i'll try monterey. Thanks

**Comment by Bedict31** [comment]
Hi so i installed monterey, my problem not is that the installer is laggy and i managed to install it. Now i'm in the oobe or setup screen, it is very laggy that i can't use the macos very well.

**Comment by Bedict31** [comment]
I just discovered that the brightness still isn't working the cursor also is laggy and it does not run in 144hz.  ![IMG_20221127_200135_1.jpg](https://user-images.githubusercontent.com/97432912/204134163-e33124c0-394f-481b-83a3-b3f141678009.jpg)

**Comment by Bedict31** [comment]
![IMG_20221127_195954.jpg](https://user-images.githubusercontent.com/97432912/204134186-94073605-8343-4c08-9654-d02cd8d24742.jpg)

**Comment by Vincent4440** [comment]
try using my older efi which was released on 31th of oct if that also not works, 
am sorry buddy i cant help you

**Comment by Vincent4440** [comment]
https://github.com/Vincent4440/ASUS-TUF-F15-OPENCORE/releases/tag/31-Oct-2022

**Comment by Bedict31** [comment]
Okay, ill try. Thank you, ill close the issue!
